### ISSUE TITLE
QA 0.1.1 using Tanzania Test Group

### ISSUE THREAD

**Issue by chrisekelley** [Tangerine-Community/Tangerine-client#205]
Verify fixes in QA:
- [x] the grid-logic skip #174 
- [x] the survey logic skip #106
- [x] and the random sequences #162
- [x] Subtest-Level Skip Logic not working #208

**Comment by chrisekelley** [comment]
Use .Subtest-Level Skip Logic Assessment to test.

**Comment by rjcorwin** [comment]
@skippskipp We're ready for another round of QA on http://databases.tangerinecentral.org/group-rti_tanzania_2016_test

I generated a new APK from the new code http://159.203.15.226/apk/krtupb

**Comment by skippskipp** [comment]
Notes on this .apk:
- Initial loading after install took about 3 minutes for login screen to show up (not a critical issue, but may be worth looking into later). 
- Resuming into a subtest affected by a random sequence is working well.
- Skipping subtests by ResultOfGrid seems to be working well.
- Uploaded test result; initial review of CSV looks good! 

Will you move this code on to the master rti_tanzania_2016 ? That's where latest content is living. No further edits to content until Sunday.

**Comment by chrisekelley** [comment]
Both group-rti_tanzania_2016 and group-rti_tanzania_2016_test are using the same source code for Tangerine-client; therefore, you may generate an APK from the APK link on group-rti_tanzania_2016. I just sent you a link to an APK generated for group-rti_tanzania_2016. Just be sure to append .arm to the link that is displayed; otherwise, it will give you an APK for Intel-based devices, which are uncommon.

Glad to see that the assessments are working properly! Pop me a note if you run into any problems.

**Comment by rjcorwin** [comment]
@chrisekelley @skippskipp Glad to hear things are going well. I will check in again tomorrow in my AM.

**Comment by rjcorwin** [comment]
Closing this issue, 0.1.1 has been released. Opened #211, QA 0.1.2.
